# Description: Counts 429 responses, to ban clients that keep going over a configured rate limit
# Note this sees the same events as nginx-excessive-reqs, but from the access log rather than the error log
[Definition]
failregex = ^<HOST>.*" 429\s
ignoreregex = 